Add version guard for UserManager#getRemainingCreatableProfileCount.
UserManager#getRemainingCreatableProfileCount does not exist in versions
older than T, thus add version guard before calling it, to avoid
NoSuchMethodError.

Bug: 286026837

Ignore-AOSP-First: fixing a bug introduced in UDC branch only

Test: atest CtsPhotoPickerTest CtsMultiUserTestCases

Change-Id: I6fa93dcca816184d5bf1c5d0cc96d13e596cb01b