KeyStoreException: Test handling of RKP failures
Test that RKP errors are handled correctly:
* Always indicated as system errors.
* Always return the error code indicating keys are missing.
* Indicated as transient where applicable.
* The right re-try policy is returned.

Bug: 227306369
Test: atest android.keystore.cts.KeyStoreExceptionTest
Change-Id: I52ca1ef949f96cf78dc06be9096e61457b52e0eb